export function CountyMethod(){return <section id="stockholm">
  <h2>Habitatytor i hela Stockholms län</h2>
  <p>Länsgränsen härleds från SCB:s RegSO 2025 för samtliga 26 kommuner. NMD2023 v2.1 från Naturvårdsverket är grundunderlag med 10 meters pixlar. Alla tio arter använder samma öppet redovisade markprofiler som Botkyrkapiloten. Det är experimentella markklassmatchningar, inte fyndsannolikheter. Fem pixlar inom länsgränsen saknar NMD-värde och lämnas utan markering.</p>
  <h3>Skötta miljöer och landsbygd</h3>
  <p>OpenStreetMaps kartlagda parker, trädgårdar, skötta gräsytor, idrottsytor, skolor, bostads- och handelsmiljöer samt stationer och andra definierade anläggningar filtreras bort. Naturlig gräsmark och betesmark undantas inte enbart för att de är gräsbevuxna. Ingen faktisk klippfrekvens är känd.</p>
  <p>Anläggningens kartlagda yta undantas både i tätort och på landsbygd. Extra buffertar runt den används endast inom SCB:s tätorter 2023: skolor och stationer upp till 100 meter, handel och centrum upp till 75 meter, övriga kategorier 15–50 meter. Punkter och linjer utan kartlagd yta får en försiktighetszon på högst 15 meter även på landsbygden. Naturmark utanför anläggningen kan därmed finnas kvar. Tätortsgränserna är ett uttryckligt produktantagande för denna skillnad, inte ett mått på besökstryck.</p>
  <p>Alla 10-meterspixlar som berör ett undantag tas bort. I utzoomat läge visas en försiktig översikt där bara homogena större block finns kvar; små habitatytor syns först vid inzoomning. Detaljvyn bevarar det ursprungliga pixelunderlaget, med mindre koordinatavrundning i kartformatet.</p>
  <h3>Väder och dataluckor</h3>
  <p>Länskartan visar enbart markstöd. Botkyrkas fem väderreferenser extrapoleras inte till hela länet. Den fördjupade mark- och väderjämförelsen finns fortsatt på <a href="/botkyrka">Botkyrkas pilotsida</a>. Jordkemi, enskilda värdträd, skötsel och ekologisk fältvalidering saknas fortfarande.</p>
  <p>Källor: <a href="https://www.naturvardsverket.se/verktyg-och-tjanster/kartor-och-karttjanster/nationella-marktackedata/ladda-ner-nationella-marktackedata/">Naturvårdsverket NMD, CC0</a>, <a href="https://www.scb.se/vara-tjanster/oppna-data/oppna-geodata/">SCB:s öppna geodata</a> och <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors, ODbL 1.0</a>. Det OSM-filtrerade länsunderlaget delas under ODbL. <a href="/data/stockholm/metadata.json">Metadata och källhashar</a> samt <a href="https://github.com/friggees/svampatlas/tree/main/scripts">reproduktionsskript</a> är tillgängliga; karttiles är öppet åtkomliga via samma webbplats.</p>
</section>;}
