import { species } from '../species/catalog';
import { habitatProfiles } from './habitat-profiles';
export function HabitatMethod(){return <section id="habitat"><h2>Experimentell habitatmodell</h2>
  <p>Markunderlag: <a href="https://geodata.naturvardsverket.se/nedladdning/marktacke/NMD2023/Basskikt_v2_x/NMD2023_Produktbeskrivning_Basskikt_NMD2023_v2_x.pdf">Naturvårdsverkets NMD2023 v2.1</a>, CC0, hämtat 27 september 2026. Det kategoriska rastret har 10 meters upplösning. Inga rastervärden saknades inom pilotens pixelmask vid importen. Marktäcke är inte jordart, pH eller observerade svampfynd; kartläggningens referensår är inte ett löfte om dagens vegetation.</p>
  <p>Vi räknar verkliga klassandelar i rutor om 250 × 250 meter, avgränsade av pilotens pixelmask. Endast pixlar i artprofilens utvalda markklasser färgas. Vatten, exploaterad mark, åker, hyggen och andra ej valda klasser ger inget markstöd. Rutor med nodata bedöms inte. Pixelgränser kan avvika upp till ungefär en halv pixel från SCB-gränsen; koordinater avrundas till sex decimaler.</p>
  <p>Markstödet är andelen matchande mark gånger 100. Det kombinerade indexet är det lägre av markstödet och artens väderbetyg. Högst 59 tillåts för svart trumpetsvamp, rödgul trumpetsvamp, röd flugsvamp och toppslätskivling eftersom särskilt viktiga lokala variabler saknas. Klassurval, denna begränsning och färggränserna 40 och 70 är öppna pilotantaganden, inte forskningsbestämda trösklar.</p>
  <p>Varje yta kopplas till den närmaste av fem fasta väderreferenser; saknat väder ersätts aldrig med en mer avlägsen referens. Kartan och listan använder samma resultat. Vid hämtfel, omladdning eller nytt svenskt dygn tas kombinerade betyg bort och markytorna blir grå. Listan visar upp till sex ytor med minst 750 meter mellan representativa punkter. Alla ytor med högsta index från 40 får mörk kant; det innebär inte att de säkert är bra svampställen.</p>
  <p>Artkällorna stödjer allmän ekologi. Översättningen till NMD-klasser är vår preliminära tolkning och behöver ekologisk expertgranskning och fältvalidering. Inga privata sparningar eller fynd används. Ingen tillträdesrätt, entré eller fyndsannolikhet bedöms.</p>
  <h3 id="platsfilter">Skogsturfilter för skötta och tätbebyggda platser</h3>
  <p>© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors, ODbL</a>. Ett avgränsat Botkyrka-uttag via Overpass hämtades 27 september 2026. Parker, trädgårdar, gräsmattor, lek- och idrottsplatser, skolor, bostadsområden, handels- och industriområden, torg, kyrkogårdar, kolonilotter, parkerings- och byggytor filtreras bort. Naturreservat och naturliga gräsmarker tas inte bort enbart på grund av att de är offentliga.</p>
  <p>Marginaler från kartlagd geometri: skola/förskola/högskola 100 m; handel/centrum/köpcentrum 75 m; torg/sjukhus/stormarknad/stadion 50 m; lek/idrott/rekreation/bassäng 30 m; bostäder/industri/parkering/bygg- och järnvägsområden 25 m; park/trädgård/gräsmatta/kyrkogård/kolonilotter 15 m. Punkter får samma radie eftersom deras verkliga utbredning saknas. Alla 10-meterspixlar som berör en undantagsyta tas bort. Det är ett försiktigt utflyktsfilter, inte en ekologisk regel; svamp kan finnas även på bortfiltrerade platser.</p>
  <p>Uppmätt besökstryck, gräsklippning och fullständig täckning saknas. En omärkt plats kan därför fortfarande vara skött eller välbesökt. Vi reducerar även markstödet med de borttagna pixlarna, så rester av en park inte ger hela rutan ett högt betyg. Ofiltrerad klassfördelning redovisas separat för insyn.</p>
  <p>Underlaget och filtreringen kan granskas: <a href="/data/botkyrka-exclusions.geojson">undantagsytor, källdatum och regler</a> · <a href="/data/botkyrka-habitat.json">härledd habitatdatabas</a>. Den OSM-härledda filtrerade databasen delas under <a href="https://opendatacommons.org/licenses/odbl/1-0/">ODbL 1.0</a>; ursprungligt NMD-underlag är CC0.</p>
  <h3>Satellitbakgrund</h3>
  <p><a href="https://cloudless.eox.at">EOxCloudless</a> by EOX IT Services GmbH (Contains modified Copernicus Sentinel data 2024 &amp; 2025). Sentinel-2-mosaik med 10 meters grundupplösning, inte livebilder eller detaljerade flygfoton. Satellitbilderna påverkar inte habitatbetyget. Byt mellan Karta och Satellit utan att förlora zoom eller vald plats; dölj habitatytorna för en ren bild.</p>
  <p>Satellittjänsten används för den icke-kommersiella piloten under <a href="https://cloudless.eox.at/documentation/license">CC BY-NC-SA 4.0 och EOX tjänstevillkor</a>. Kommersiell drift kräver separat licens eller annan leverantör. EOX får bildrutorna som behövs för ditt kartutsnitt; vi skickar inte sparade platser eller anteckningar till dem. Ingen offlinehämtning görs.</p>
  <h3>Artprofiler och källor</h3><p>Källor lästa 27 september 2026. Texter sammanfattade; inga artbilder importerade.</p>
  {species.map(s=><div key={s.id}><h4>{s.name}</h4><p>{habitatProfiles[s.id].ecology} {habitatProfiles[s.id].gaps} <a href={habitatProfiles[s.id].source}>Artkälla</a>.</p><p>NMD-klasser i pilotprofilen: {habitatProfiles[s.id].codes.join(', ')}.</p></div>)}
</section>;}
