export function WeatherMethod() {
  return <section id="vader"><h2>Väderbedömning för svamp</h2>
    <p>Jämförelsen använder 14 avslutade dygn från <a href="https://open-meteo.com/en/docs">Open-Meteo / DWD ICON</a>: temperatur, regn, relativ luftfuktighet och modellerad markfuktighet på 3–9 cm djup. Dagens ofullständiga dygn och framtida prognoser räknas inte in. Dygn följer svensk tid, även vid sommartidsbyte.</p>
    <p>Temperatur väger 35 %, regn 25 %, luftfuktighet 15 % och markfuktighet 25 %. Längre temperaturstress, torra perioder och frost minskar därefter indexet. Gränser, vikter och grupperingen av arter är preliminära pilotantaganden, inte biologiska optima som har validerats för Botkyrka. Samma väder kan ge olika betyg för olika artprofiler.</p>
    <p>Resultatet är ett väderindex på 0–100, inte procentuell fyndchans. En gynnsam väderperiod räcker inte om rätt skog, värdträd, jord eller mycel saknas. Sådant habitatunderlag ingår ännu inte. Olika jordarter kan dessutom ha olika tillgänglig fuktighet vid samma modellerade vatteninnehåll.</p>
    <p>Väderdata bygger på modellrutor som är flera kilometer stora. Fem referensområden jämförs; referenspunkterna är inte utpekade fyndplatser. Små skillnader är osäkra, närliggande områden kan dela vädercell och modellen beskriver inte mikroklimat i en viss glänta. Endast dessa fasta offentliga referenspunkter skickas till vädertjänsten, aldrig dina privata platsnamn, anteckningar eller exakta sparade koordinater.</p>
    <p>Forskningsbakgrund: <a href="https://www.fs.usda.gov/pnw/pubs/pnw_gtr576.pdf">USDA:s översikt om kantarellers ekologi</a> och <a href="https://italianmycology.unibo.it/article/view/16464">Salerni med flera om klimat och stensopp</a> stödjer att väder och lokala förhållanden påverkar fruktkroppsbildning. De ger inte stöd för att överföra våra numeriska pilotgränser direkt till alla arter eller svenska miljöer.</p>
    <p>Data: <a href="https://open-meteo.com/">Open-Meteo</a>, <a href="https://open-meteo.com/en/licence">CC BY 4.0</a>. Gratis-API används för den lokala piloten; <a href="https://open-meteo.com/en/terms">villkor för kommersiell användning</a> behöver hanteras före sådan drift. Värden kan mellanlagras en timme. Saknade dygn eller fuktvärden ger inget betyg; gårdagens analysfönster återanvänds inte efter ett nytt dygn.</p>
  </section>;
}
