import {chromium,expect} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';
import {randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const admin=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SECRET_KEY,{auth:{persistSession:false}});
const email=`svampatlas-browser-${randomUUID()}@example.com`,password=`Test-${randomUUID()}!`;
const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true});
if(error)throw new Error(`Unable to create synthetic test account: ${error.status}`);
let browser;
try{
 browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3000';
 await page.goto(`${base}/konto`);await page.getByLabel('E-postadress').fill(email);await page.getByLabel('Lösenord').fill(password);await page.getByRole('button',{name:'Logga in',exact:true}).click();await page.waitForURL(`${base}/`);
 await page.locator('.map-canvas canvas').waitFor();
 await expect.poll(()=>page.locator('.map-canvas').evaluate(e=>e.getBoundingClientRect().height),{message:'Map container must have a visible height'}).toBeGreaterThan(300);
 await expect(page.getByText('Kartan kunde inte laddas helt.',{exact:false})).toHaveCount(0);
 await page.getByLabel('Latitud',{exact:true}).fill('59.444');await page.getByLabel('Longitud',{exact:true}).fill('18.068');await page.getByLabel('Platsens namn').fill('Browserns testglänta');await page.getByLabel('Anteckning').fill('Syntetiskt test, raderas direkt.');await page.getByRole('button',{name:'Spara min plats'}).click();await page.getByText('Platsen är sparad under Mina platser.').waitFor();
 await page.goto(`${base}/sparat`);await page.getByRole('heading',{name:'Browserns testglänta'}).waitFor();assert.ok((await page.getByRole('link',{name:'Vägbeskrivning'}).getAttribute('href')).includes('59.444%2C18.068'));
 await page.reload();await page.getByRole('heading',{name:'Browserns testglänta'}).waitFor();
 await page.getByRole('button',{name:'Ta bort Browserns testglänta',exact:true}).click();await page.getByRole('button',{name:'Ta bort',exact:true}).click();await page.getByRole('heading',{name:'Din nästa favoritplats väntar'}).waitFor();
 await page.goto(`${base}/botkyrka`);await page.getByRole('button',{name:'Utforska området'}).click();await page.getByRole('heading',{name:'Kartytor för kantarell'}).waitFor();
 await page.getByRole('heading',{name:'Områden efter väderbetyg'}).waitFor({timeout:25000});
 await expect(page.locator('.weather-ranking li button')).toHaveCount(5);
 await expect(page.locator('.weather-score strong')).toHaveText(/^\d{1,3}$/);
 await page.getByRole('button',{name:'Visa väder för Tullinge',exact:true}).click();
 await expect(page.getByLabel('Latitud',{exact:true})).toHaveValue('59.2');
 await expect(page.getByLabel('Longitud',{exact:true})).toHaveValue('17.9');
 await page.getByRole('combobox',{name:'Välj svamp'}).click();
 await page.getByRole('option',{name:'Trattkantarell',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Väderläge för trattkantarell'})).toBeVisible();
 await expect(page.locator('.weather-detail')).toContainText('4–13 °C i pilotprofilen');
 await page.locator('.weather-method summary').click();
 await expect(page.locator('.weather-method tbody tr')).toHaveCount(14);
 await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'Mobile overflow');
 await expect.poll(()=>page.locator('.map-canvas').evaluate(e=>e.getBoundingClientRect().height),{message:'Mobile map must remain visible'}).toBeGreaterThan(300);
 await page.route('**/api/weather',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Synthetic outage'})}));
 await page.getByRole('button',{name:'Uppdatera väder',exact:true}).click();
 await expect(page.getByRole('alert').filter({hasText:'Väderanalysen kunde inte hämtas'})).toBeVisible();
 await expect(page.locator('.weather-score')).toHaveCount(0);
 await page.unroute('**/api/weather');
 await page.getByRole('button',{name:'Försök igen',exact:true}).click();
 await expect(page.locator('.weather-score strong')).toHaveText(/^\d{1,3}$/,{timeout:25000});
 await page.goto(`${base}/arter`);await page.getByRole('heading',{name:'Toppslätskivling',exact:true}).waitFor();
 assert.deepEqual(errors,[]);console.log('PASS: login → save → reload → directions → delete; live weather ranking, species switch, map selection, 14-day history, outage hides scores, retry; mobile layout; species catalog; no page errors.');
}finally{await browser?.close();const {error}=await admin.auth.admin.deleteUser(data.user.id);if(error)throw new Error('Browser test user cleanup failed');console.log('Browser test account removed.');}
